/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2018-01-29-11e6f91a4e"
#endif /* AVUTIL_FFVERSION_H */
