/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2018-01-24-f0eb8ea1f5"
#endif /* AVUTIL_FFVERSION_H */
