/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2017-10-10-62ff55193a"
#endif /* AVUTIL_FFVERSION_H */
